### ISSUE TITLE
Link XBT

### ISSUE THREAD

**Issue by tojoaijo** [TTsWeb/u232-v5-xbt-mariadb-php7#1]
Hi,
The link to download XBT on the script doesn't work (http://xbt.googlecode.com/svn/trunk/xbt/misc), line 180 and 181
So I can't continue the script.
Can you help me please?
Thanks :)

**Comment by TTsWeb** [comment]
there is like 5 different scripts located in this so I dont know what one trying to use..........................................................................
So no i cant help you!!!
best bet is to look at https://github.com/TTsWeb/u232-v5-xbt-mariadb-php7/blob/master/u232-v5-deb9.sh  or https://github.com/TTsWeb/u232-v5-xbt-mariadb-php7/blob/master/u232-v5.sh
